name: Amazon Monitor

on:
  schedule:
    - cron: "0 */4 * * *" # 4時間ごと
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npx playwright install

      - name: Set Google Sheets ID
        run: echo "GOOGLE_SHEETS_ID=${{ secrets.GOOGLE_SHEETS_ID }}" >> $GITHUB_ENV

      - name: Set Chatwork Token
        run: echo "CHATWORK_TOKEN=${{ secrets.CHATWORK_TOKEN }}" >> $GITHUB_ENV

      - name: Run Monitor
        run: node index.js
